name: Playwright Daily Cronjob

on:
  schedule:
    - cron: '0 18 * * *'  # เวลา 01:00 AM ตามเวลาไทย (UTC+7)
  push:
    branches:
    - main
  workflow_dispatch:  # ทำให้สามารถรัน workflow ได้ด้วยตนเอง
     
jobs:
  test:
    runs-on: ubuntu-22.04 # หรือ ubuntu-24.04 ถ้าพร้อมเปลี่ยน

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install
    
    - name: Decode Service Account Key from encoded_key.txt
      run: |
        base64 -d tests/encoded_key.txt > tests/service-operation-439703-9bc8c8165988.json
        
    - name: Run Playwright tests
      run: npx playwright test
