name: Playwright Daily Cronjob

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ทำให้สามารถรัน workflow ได้ด้วยตนเอง
     
jobs:
  test:
    runs-on: ubuntu-22.04 # หรือ ubuntu-24.04 ถ้าพร้อมเปลี่ยน

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install
    
    - name: Create Service Account Key file
      run: |
        mkdir -p tests
        echo $SERVICE_ACCOUNT_KEY | base64 -d > /tests/service-operation-439703-9bc8c8165988.json
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Run Playwright tests
      run: npx playwright test
